### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by gadenbuie** [vincentmajor/SEER_read_fwf#1]
I'm building out a small R package to read SEER data and your script provides a great place to start. Would you consider adding an open source license, such as the [MIT license](https://choosealicense.com/licenses/mit/) to this repo? It would make it easier for me and others to re-use your code guilt-free.

I'll also add you as a contributor to the package I put together; would the information [here](https://github.com/vincentmajor/mimicfilters/blob/master/DESCRIPTION) be good to add?

**Comment by vincentmajor** [comment]
Hi! 
Yep, fair enough, I added the MIT license. Good luck!

And yes, that contact info is fine.

**Comment by gadenbuie** [comment]
Awesome, thanks!
